name: Doxygen Docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Docs
        run: doxygen Doxyfile

      - name: Clone kejunp.github.io repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/kejunp/kejunp.github.io.git ../gh-pages

      - name: Copy generated docs to target location
        run: |
          rm -rf ../gh-pages/docs/pebbl
          mkdir -p ../gh-pages/docs/pebbl
          cp -r docs/html/* ../gh-pages/docs/pebbl/

      - name: Commit and push docs
        run: |
          cd ../gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/pebbl
          git diff --cached --quiet || git commit -m "Update pebbl Doxygen docs"
          git push